### PR TITLE
addon installation command

### PR DESCRIPTION
**Pull request by 4www**
super small but thought why not

### CODE REVIEW

**Comment by MattMSumner** [comment]
I think this is now `ember install torii-fire` in the latest `ember-cli`. Is that preferable?

**Comment by Ghostavio** [comment]
yes, `ember install torii-fire` is the way to go

**Comment by MattMSumner** [comment]
@hugovieilledent if you make the change I'll go ahead and merge :+1:

**Comment by 4www** [comment]
here :)

**Pull request merged**
